### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /lib/PelIfd.php on line 805

### ISSUE THREAD

**Issue by rudolphos** [samnabi/panoramio-dump#2]
First of all I wanted to say this is a great script, the only one working I could find..

I'm using this on cygwin 64bit version, and after 160~ pictures it shows that memory has been exceeded.

I don't know much about this stuff, but how can memory be exceed, does it load unfinished downloads in cache/ram, and how could that be if only one file can be downloaded simultaneously.. I have 3 GB free RAM when I ran the command.

```
Administrator@x /cygdrive/d/cygwin64/pdm
$ php index.php
photo.jpg ... PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /cygdrive/d/cygwin64/pdm/lib/PelIfd.php on line 805
```

I read these tutorials:

http://stackoverflow.com/questions/561066/fatal-error-allowed-memory-size-of-134217728-bytes-exhausted-codeigniter-xml
http://stackoverflow.com/questions/9276212/php-settings-memory-limits-1024m-does-not-work

But couldn't find any memory setting on 805th line.. So I added it
`ini_set('memory_limit', '3028M');` 
Then ran again and checked the task manager, and memory for php process grew to 3000 MB then showed the same error message in console.

Also added it in index.php, but that didn't work.
Also edited memory_limit to 512M in php5 config file 'php.ini', didn't fix anything.

**Comment by rudolphos** [comment]
bump

**Comment by samnabi** [comment]
What settings are you using at the beginning of `index.php`?

**Comment by rudolphos** [comment]
I haven't changed anything in the original script, because it didn't work when I added memory settings, etc..
Currently I have only set the **user ID** (numbers) and **qty** = **2606** , **spaces in filename** is set to **true**.

**Comment by samnabi** [comment]
What happens if you reduce the `qty`? The script will pick up where it left off if you run it multiple times with a reduced qty.

**Comment by rudolphos** [comment]
I reduced qty to 280 and the problem still occurs. It can't download image which is around 2MB, even though the max size it downloaded was around 4,9 MB.

```
COMPUTER@COMPUTER /cygdrive/c/pdm
$ php index.php
photo.jpg ... PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 72 bytes) in /cygdrive/c/pdm/lib/PelIfd.php on line 805

```

Also getting a different error after 158 images downloaded

`... PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 5903096 bytes) in /cygdrive/d/cygwin64/pdm/lib/PelJpeg.php on line 527`

**Comment by samnabi** [comment]
Unfortunately, Panoramio has removed access to their `http://www.panoramio.com/map/get_panoramas.php` endpoint. This means that `panoramio-dump` has no way of getting the filenames so it can download the photos.

I've added a notice to the README that this tool doesn't work anymore. Sorry.
